# docker-compose.yml
version: '3.10'

services:
  chainlit-chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
    volumes:
      - ./knowledge_graph.json:/app/knowledge_graph.json:ro
      - ./logs:/app/logs
      - ./.chainlit:/app/.chainlit
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

